### ISSUE TITLE
commits has no `additions` column?

### ISSUE THREAD

**Issue by iwasherefirst2** [augmentable-dev/askgit#73]
I don't get that query:

`SELECT count(*) AS commits, SUM(additions) AS additions, SUM(deletions) AS  deletions, author_email FROM commits GROUP BY author_email ORDER BY commits` 

According to the docs there is no  `additions` and `deletions` column for the `commits` table.
Are they missing in the docs?

![image](https://user-images.githubusercontent.com/1765602/99736489-c01dc600-2ac6-11eb-9000-65a50ee1f709.png)

**Comment by patrickdevivo** [comment]
Hi @iwasherefirst2 sorry about that! That looks like a discrepancy in the README/sample queries. Commit additions/deletions were recently removed from the `commits` table since they now can be pulled from the `stats` table. I think the equivalent example query now should look something like:

```sql
SELECT count(DISTINCT commits.id) AS commits, SUM(additions) AS additions, SUM(deletions) AS deletions, author_email
FROM commits LEFT JOIN stats ON commits.id = stats.commit_id
GROUP BY author_email ORDER BY commits
```

It is a bit more complex as it involves joining with the `stats` table. I will update the README to address this - thanks for surfacing and I hope that helps!
